LAB8/shop_back/api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products_list, name='products_list'),
    path('products/<int:id>/', views.product_detail, name='product_detail'),
    path('categories/', views.categories_list, name='categories_list'),
    path('categories/<int:id>/', views.category_detail, name='category_details'),
    path('categories/<int:id>/products/', views.category_products, name='category_products'),
]

LAB8/shop_back/shop_back/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls'))
]

LAB8/shop_back/api/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)

    def to_json(self):
        return {
            'id': self.id,
            'name': self.name,
        }


class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=100, default="None")
    price = models.FloatField(default=0)
    description = models.TextField(default='')
    count = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    def to_json(self):
        return {
            'id': self.id,
            'name': self.name,
            'category': self.category,
            'price': self.price,
            'description': self.description,
            'count': self.count,
            'is_active': self.is_active,
        }

LAB8/shop_back/api/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, Http404
from django.template import loader
from .models import Product, Category

# Create your views here.

def index(request):
    return render(request, 'index.html', locals())

def products_list(request):
    products = Product.objects.all()
    products_json = [product.to_json() for product in products]
    # return JsonResponse(products_json, safe=False)
    return render(request, 'products_list.html', {'products':products})

def product_detail(request, id):
    try:
        product = Product.objects.get(id=id)
    except Product.DoesNotExist as e:
        raise Http404("Product does not exist")
    return render(request, 'product_detail.html', {'product':product})
    # return JsonResponse(product.to_json())

def categories_list(request):
    categories = Category.objects.all()
    context = {'categories':categories}
    categories_json = [category.to_json() for category in categories]
    # return JsonResponse(categories_json, safe=False)
    return render(request, 'categories_list.html', context)


def category_products(request, id):
    # try:
    #     category = Category.objects.get(id=id)
    # except Category.DoesNotExist as exception:
    #     return Http404("Category does not exist")
    #     # return JsonResponse({'exception': str(exception)}, status=400)
    # # return JsonResponse(category.to_json())
    # return render(request, 'category_details.html', {'category':category})
    try:
        # categories = Category.objects.get(id=id)
        # products = Product.objects.filter(category=categories.name)
        category = Category.objects.get(id=id)
        products = Product.objects.filter(category = category.name)
        context = {
            'category': category,
            'products': products,
        }
    except Category.DoesNotExist as e:
        return Http404("Category is empty")
    return render(request, 'category_products.html', context)



def category_detail(request, id):
    try:
        categories = Category.objects.get(id=id)
        products = Product.objects.filter(category=categories.name)
    except Category.DoesNotExist as e:
        return Http404("Category is empty")
    return render(request, 'category_details.html', {'products':products, 'categories': categories})
    # return JsonResponse([i.to_json() for i in products], safe=False)

LAB8/shop_back/api/templates/categories_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Categories</title>
    <style>
        a {
            text-decoration: none;
            color: black;
            text-align: center;
        }
        ul {
            position: absolute;
            left: 40%;
            top: 5%;

        }
    </style>
</head>
<body>
    {% if categories %}
        <ul>
        {% for category in categories %}
            <h2><a href="{% url 'api:categories_list' %}">{{ category.name }}</a></h2>
        {% endfor %}
        </ul>
    {% else %}
        <p>No categories are available.</p>
    {% endif %}
</body>
</html>

LAB8/shop_back/api/templates/category_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Products</title>
    <style>
        h1 {
            text-align: center;
        }
        a {
            text-decoration: none;
            color: black;
        }
    </style>
</head>
<body>
<h1>{{ categories.name }}</h1>
    {% if products %}
        <ul>
        {% for product in products %}
            <li><h3><a href="{% url 'api:product_detail' product.id %}">{{ product.name }}</a></h3></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No products are available.</p>
    {% endif %}

</body>
</html>

LAB8/shop_back/api/templates/category_products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Products</title>
</head>
<body>
<h1>{{ Category.name }}</h1>
{% block content %}
    {% for product in products %}
        <ul>
            <li><h1>{{product.name}}</h1>
            <p>{{product.description}}</p>
        <h2>{{product.price}}$</h2>
        <h3>Осталось: {{product.count}} шт.</h3>
                </li>
        <br>
        </ul>
    {% endfor %}
{% endblock %}
</body>
</html>

LAB8/shop_back/api/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lab8</title>
    <style>
        ul {
            text-align: center;
            position: absolute;
            top: 40%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>
<body>
<ul>
    <h1><a href="{% url 'api:products_list' %}"> All Products </a></h1>
    <h1><a href="{% url 'api:categories_list' %}"> Categories </a></h1>
</ul>
</body>
</html>

LAB8/shop_back/api/templates/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Products</title>
    <style>
        h1 {
            text-align: center;
        }

    </style>
</head>
<body>
    {% if product.is_active %}
        <h1>{{product.name}}</h1>
        <p>{{product.description}}</p>
        <h2>{{product.price}}$</h2>
        <h3>Осталось: {{product.count}} шт.</h3>
    {% else %}
        <p>No product is not active now</p>
    {% endif %}
</body>
</html>

LAB8/shop_back/api/templates/products_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Products</title>
    <style>
        a {
            text-decoration: none;
            color: black;
        }
    </style>
</head>
<body>
    {% if products %}
        <ul>
        {% for product in products %}
            <li><h2><a href="{% url 'api:product_detail' product.id %}">{{ product.name }}</a></h2></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No products are available.</p>
    {% endif %}

</body>
</html>